### ISSUE TITLE
Confusion with Dataset

### ISSUE THREAD

**Issue by tanmay2642** [ankiteciitkgp/botnetDetection#1]
Hi I am trying to build result from your code. But there is some confusion regarding the dataset. Can you please elaborate on the dataset you used. ISCX provides a pcap for same. However there is no mention of conversion of pcap->xml. Do we need to use any tool(Argus, tcpflow) to generate the same?

**Comment by ankiteciitkgp** [comment]
Hi Tanmay,
As far as I remember ISCX dataset also had XML files corresponding to the PCAP files which we used to extract features. Otherwise, If you want to extract features from pcap file directly you can use Argus to generate netflows and extract features out of it.

**Comment by tanmay2642** [comment]
Hi,
I tried using Argus to generate XML of netflows but it does not parse the pcap correctly. Can you please provide me the xml files that were used during your training?

**Comment by ankiteciitkgp** [comment]
Unfortunately I lost my dataset due to a crash on my system. You can try
CTU-13 dataset it is a better dataset and I have tried Argus on that.

On 04-Dec-2017 1:39 PM, "Tanmay" <notifications@github.com> wrote:

Hi,
I tried using Argus to generate XML of netflows but it does not parse the
pcap correctly. Can you please provide me the xml files that were used
during your training?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ankiteciitkgp/botnetDetection/issues/1#issuecomment-348888579>,
or mute the thread

**Comment by tanmay2642** [comment]
My correspondence mail is tanmay2642@gmail.com

**Comment by tanmay2642** [comment]
Sure Thank You!

**Comment by tanmay2642** [comment]
Hi,
Just one more help needed. Can you point me to the commands that were used for processing dataset(pcap) in argus. I could not find any documentation that has the relevant information of the same. It would really help me to move forward.
Thanks!

**Comment by ankiteciitkgp** [comment]
You have to first convert PCAP to Biargus file and then Biargus file to Binetflow

PCAP -> Biargus
argus -F ./confs/argus.conf -r  **pcap_file_name**  -w  **biargus_file_name**

Biargus -> Binetflow
ra -F ./confs/ra.conf -n -Z b -r **biargus_file_name** |sort -n > **binetflow_file_name**

where argus.conf and ra.conf are your config files
